"""Phase 2b against synthetic media: staging, the three decode paths, the two
derivatives, and what happens to a file that will not decode.

No path from config.toml and no real photograph. The video is generated by
ffmpeg's own `testsrc`, the stills are drawn here, and the raw path is exercised
where it can be without shipping a camera file -- `_apply_flip` and the
preview/demosaic threshold are the parts that carry the decision.
"""

from __future__ import annotations

import dataclasses
import io
import json
import shutil
import sqlite3
import subprocess
from pathlib import Path

import numpy as np
import pytest
from PIL import Image

from photolib import db, decode, phase2b, triage
from photolib.config import Config
from photolib.phase2a import deriv_path
from photolib.thumbnails import thumb_path

FFMPEG = shutil.which("ffmpeg")
EXIFTOOL = shutil.which("exiftool")
needs_ffmpeg = pytest.mark.skipif(FFMPEG is None, reason="ffmpeg is not on PATH")
needs_exiftool = pytest.mark.skipif(EXIFTOOL is None, reason="exiftool is not on PATH")


# --- material ----------------------------------------------------------------


def card(width: int = 900, height: int = 600) -> Image.Image:
    """A frame no rotation of which resembles any other.

    Asymmetric in both axes and in colour, for the same reason
    `tests/test_phase2a.py` says: a four-quadrant card has the same dHash as its
    own 180 degree rotation, so it would let an orientation mistake pass.
    """
    y, x = np.mgrid[0:height, 0:width]
    base = 40 + 90 * (x / width) + 50 * (y / height)
    base[: height // 3, : width // 3] = 250
    base[2 * height // 3 :, : width // 4] = 5
    array = np.repeat(base[:, :, None], 3, axis=2).astype(np.uint8)
    array[:, :, 1] = np.clip(array[:, :, 1] * 0.7, 0, 255)
    return Image.fromarray(array)


def jpeg(image: Image.Image, **save) -> bytes:
    out = io.BytesIO()
    image.save(out, format="JPEG", quality=92, **save)
    return out.getvalue()


def brightest_quadrant(image: Image.Image) -> str:
    array = np.asarray(image.convert("L"), dtype=np.float64)
    height, width = array.shape
    means = {
        "tl": array[: height // 2, : width // 2].mean(),
        "tr": array[: height // 2, width // 2 :].mean(),
        "bl": array[height // 2 :, : width // 2].mean(),
        "br": array[height // 2 :, width // 2 :].mean(),
    }
    return max(means, key=means.get)


@pytest.fixture
def config(tmp_path: Path, migrated: tuple[Path, Path]) -> Config:
    return Config(
        photos_root=tmp_path / "photos",
        restic_repo=tmp_path / "restic",
        mediavault_root=tmp_path / "MediaVault",
        mediavault_manifest_db=tmp_path / "MediaVault" / "state" / "manifest.sqlite3",
        vault_root=tmp_path / "vault",
        staging_root=tmp_path / "vault" / ".staging",
        deriv_root=tmp_path / "vault" / "deriv",
        meta_root=tmp_path / "vault" / "meta",
        thumb_root=tmp_path / "thumb",
        catalog_db=migrated[0],
        state_db=migrated[1],
        backup_root=tmp_path / "backups",
        reveal_root=tmp_path / "MediaVault" / "objects",
        restic_password_command="true",
    )


def make_video(path: Path, *, size: str = "320x240", seconds: int = 2) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [FFMPEG, "-nostdin", "-hide_banner", "-loglevel", "error", "-y",
         "-f", "lavfi", "-i", f"testsrc=duration={seconds}:size={size}:rate=10",
         "-pix_fmt", "yuv420p", str(path)],
        check=True, capture_output=True,
    )
    return path


def sink_for(conn, config: Config, long_edge: int | None = 4000) -> phase2b.Sink:
    """A `Sink` with the two metadata scalars stubbed, so a test that is about
    the pixels does not also need a manifest or an exiftool."""
    return phase2b.Sink(conn, config, {}, lambda item, result: (long_edge, None, False))


def insert_file(conn, sha256: str, ext: str, size: int, *, state: str, relpath: str | None):
    conn.execute(
        "INSERT INTO file (sha256, size, ext, kind, vault_relpath, state, feature_ver)"
        " VALUES (?,?,?,'image',?,?,'{}')",
        (sha256, size, ext, relpath, state),
    )


# --- the substrate and the tile ----------------------------------------------


def test_one_decode_produces_every_output():
    result = phase2b.decode_still(jpeg(card(3000, 2000)), phase2b.STILL_MAX_PIXELS)

    substrate = Image.open(io.BytesIO(result["substrate"]))
    tile = Image.open(io.BytesIO(result["tile"]))
    assert substrate.format == "WEBP" and tile.format == "WEBP"
    assert max(substrate.size) == phase2b.SUBSTRATE_EDGE
    assert max(tile.size) == phase2b.GRID_EDGE
    assert substrate.size == (result["deriv_w"], result["deriv_h"])
    # The native dimensions are the source's, not the substrate's.
    assert (result["native_w"], result["native_h"]) == (3000, 2000)
    assert isinstance(result["phash"], int) and isinstance(result["dhash"], int)
    assert isinstance(result["thumbhash"], bytes) and result["thumbhash"]
    assert result["quality"]["sharpness"] > 0
    assert result["quality"]["incomplete_decode"] == 0


def test_a_small_frame_is_never_upscaled():
    result = phase2b.decode_still(jpeg(card(200, 150)), phase2b.STILL_MAX_PIXELS)
    assert (result["deriv_w"], result["deriv_h"]) == (200, 150)
    assert Image.open(io.BytesIO(result["tile"])).size == (200, 150)


def test_exif_orientation_is_applied_before_anything_is_measured():
    """A JPEG carrying orientation 6 is stored turned and must come back upright.

    Measured by where the bright corner lands, not by the aspect: orientations 2,
    3 and 4 leave the aspect alone, so an aspect assertion would pass on a file
    that was never turned at all.
    """
    upright = card(900, 600)
    # Orientation 6 is undone by ROTATE_270, so the stored pixels are the
    # upright frame turned the other way.
    stored = upright.transpose(Image.ROTATE_90)
    exif = Image.Exif()
    exif[0x0112] = 6
    payload = jpeg(stored, exif=exif)

    result = phase2b.decode_still(payload, phase2b.STILL_MAX_PIXELS)
    substrate = Image.open(io.BytesIO(result["substrate"]))
    assert substrate.width > substrate.height
    assert brightest_quadrant(substrate) == brightest_quadrant(upright)


def test_a_truncated_still_is_decoded_and_flagged():
    payload = jpeg(card(900, 600))
    result = phase2b.decode_still(payload[: len(payload) // 2], phase2b.STILL_MAX_PIXELS)
    assert result["quality"]["incomplete_decode"] == 1
    assert result["substrate"]


def test_an_oversized_still_is_refused_before_its_pixels_load():
    with pytest.raises(ValueError, match="exceeds the"):
        phase2b._open_still(jpeg(card(900, 600)), 1000)


def test_the_still_cap_is_higher_than_the_inherited_one():
    """The corpus holds 91-147 megapixel panoramas; Phase 2a's cap was sized for
    1536px derivatives and refuses them."""
    from photolib import decode

    assert phase2b.STILL_MAX_PIXELS > decode.MAX_PIXELS
    assert phase2b.STILL_MAX_PIXELS > 147_098_760


# --- video -------------------------------------------------------------------


@needs_ffmpeg
def test_a_poster_frame_becomes_a_substrate_and_a_tile(tmp_path: Path):
    path = make_video(tmp_path / "clip.mp4")
    result = phase2b.decode_video((str(path), FFMPEG, 30.0), decode.MAX_PIXELS)

    assert (result["native_w"], result["native_h"]) == (320, 240)
    assert result["source"] == "poster:ffmpeg"
    assert Image.open(io.BytesIO(result["substrate"])).size == (320, 240)
    assert max(Image.open(io.BytesIO(result["tile"])).size) <= phase2b.GRID_EDGE
    assert result["quality"]["sharpness"] > 0


@needs_ffmpeg
def test_a_video_larger_than_the_poster_bound_is_scaled_and_records_no_dimensions(tmp_path):
    """Above POSTER_EDGE the frame is no longer the source's own size, so it
    contributes no `width`/`height` rather than a resampled pair passed off as
    native."""
    path = make_video(tmp_path / "big.mp4", size="3200x1800", seconds=1)
    result = phase2b.decode_video((str(path), FFMPEG, 60.0), decode.MAX_PIXELS)
    assert result["native_w"] is None and result["native_h"] is None
    assert max(Image.open(io.BytesIO(result["substrate"])).size) == phase2b.SUBSTRATE_EDGE


@needs_ffmpeg
def test_scale_precedes_thumbnail_so_the_filter_buffer_is_bounded(tmp_path: Path):
    """The regression that failed 101 4K videos: `thumbnail=N` buffers N frames,
    and buffering them at the source resolution exceeded the worker memory cap.
    The order is the fix, so the order is what is asserted."""
    from photolib.phase2b import POSTER_EDGE, POSTER_FRAMES

    seen: dict[str, list] = {}
    real = subprocess.run

    def spy(command, **kwargs):
        seen["command"] = command
        return real(command, **kwargs)

    path = make_video(tmp_path / "clip.mp4")
    subprocess.run = spy
    try:
        phase2b._poster_frame(FFMPEG, str(path), 30.0)
    finally:
        subprocess.run = real

    graph = seen["command"][seen["command"].index("-vf") + 1]
    assert graph.index("scale") < graph.index("thumbnail")
    assert f"thumbnail={POSTER_FRAMES}" in graph
    assert str(POSTER_EDGE) in graph


@needs_ffmpeg
def test_a_video_that_is_not_a_video_raises_rather_than_hanging(tmp_path: Path):
    path = tmp_path / "notreally.mts"
    path.write_bytes(b"export * from './set.mjs';\n")  # 295 real ones look exactly like this
    with pytest.raises(ValueError, match="produced no frame"):
        phase2b._poster_frame(FFMPEG, str(path), 30.0)


# --- raw ---------------------------------------------------------------------


def test_the_raw_flip_codes_turn_the_preview_the_way_libraw_means():
    upright = card(900, 600)
    for flip, inverse in ((3, Image.ROTATE_180), (5, Image.ROTATE_90), (6, Image.ROTATE_270)):
        stored = upright.transpose(inverse)
        assert brightest_quadrant(phase2b._apply_flip(stored, flip)) == brightest_quadrant(upright)
    # 0 is upright, and an unknown code is left alone rather than guessed at.
    assert phase2b._apply_flip(upright, 0) is upright
    assert phase2b._apply_flip(upright, 9) is upright


def test_the_preview_threshold_is_the_substrate_edge():
    """A 504x376 preview -- what this corpus's 146 DNG actually carry -- cannot
    make a 1536px substrate, which is why the choice is a threshold and not a
    format preference."""
    assert phase2b.RAW_PREVIEW_MIN_EDGE == phase2b.SUBSTRATE_EDGE
    assert max(504, 376) < phase2b.RAW_PREVIEW_MIN_EDGE


# --- the sink: two files, then one row ---------------------------------------


def test_a_decoded_file_lands_as_two_derivatives_and_one_row(conn, config: Config):
    sha = "a" * 64
    insert_file(conn, sha, ".jpg", 10, state="read", relpath="objects\\x.blob")
    item = phase2b.Item(sha, ".jpg", "unused", staged=False)
    sink = sink_for(conn, config)

    sink.ok(item, phase2b.decode_still(jpeg(card(3000, 2000)), phase2b.STILL_MAX_PIXELS))
    sink.flush()

    assert deriv_path(config.deriv_root, sha).is_file()
    assert thumb_path(config.thumb_root, sha).is_file()
    row = conn.execute(
        "SELECT phash, dhash, thumbhash, quality, feature_ver, deriv_w, deriv_h, deriv_rot,"
        " width, height, dims_src FROM file WHERE sha256 = ?", (sha,)
    ).fetchone()
    assert row[0] is not None and row[1] is not None and row[2]
    quality = json.loads(row[3])
    assert quality["composite_quality"] == pytest.approx(quality["composite_quality"])
    assert set(json.loads(row[4])) == {"phash", "dhash", "thumbhash", "quality"}
    assert json.loads(row[4])["quality"].endswith("deriv1536:decode")
    assert (row[5], row[6]) == (1536, 1024)
    assert row[7] == 0  # nothing was rotated: the substrate is produced upright
    assert (row[8], row[9], row[10]) == (3000, 2000, "decode")


def test_existing_dimensions_are_never_overwritten(conn, config: Config):
    """Anything already measured -- by the MediaVault adoption or by `probe` --
    is better established than this, and `dims_src` must not drift from it."""
    sha = "b" * 64
    insert_file(conn, sha, ".jpg", 10, state="read", relpath="objects\\x.blob")
    conn.execute(
        "UPDATE file SET width = 111, height = 222, dims_src = 'header' WHERE sha256 = ?", (sha,)
    )
    sink = sink_for(conn, config)
    sink.ok(
        phase2b.Item(sha, ".jpg", "unused", staged=False),
        phase2b.decode_still(jpeg(card(900, 600)), phase2b.STILL_MAX_PIXELS),
    )
    sink.flush()
    assert conn.execute(
        "SELECT width, height, dims_src FROM file WHERE sha256 = ?", (sha,)
    ).fetchone() == (111, 222, "header")


def test_a_failure_is_recorded_rather_than_left_null(conn, config: Config):
    """NULL is indistinguishable from "not attempted", which would re-read 407
    broken files on every run for ever."""
    sha = "c" * 64
    insert_file(conn, sha, ".jpg", 3, state="read", relpath="objects\\x.blob")
    sink = sink_for(conn, config)
    sink.failed(phase2b.Item(sha, ".jpg", "unused", staged=False), "error: no")
    sink.flush()

    quality = conn.execute("SELECT quality FROM file WHERE sha256 = ?", (sha,)).fetchone()[0]
    assert json.loads(quality) == {"error": "error: no"}
    assert phase2b.worklist(conn, config) == []  # and so it is not tried again


def test_clear_errors_leaves_alone_what_this_module_cannot_redo(conn, config: Config):
    """Phase 2a records its decode errors in the same shape. Clearing one here
    would take the row back to NULL with nothing in this worklist to fill it."""
    insert_file(conn, "d" * 64, ".jpg", 1, state="read", relpath="a")
    insert_file(conn, "e" * 64, ".svg", 1, state="read", relpath="b")
    insert_file(conn, "f" * 64, ".jpg", 1, state="pending", relpath="c")
    conn.execute("UPDATE file SET quality = '{\"error\": \"x\"}'")

    assert phase2b.clear_errors(conn) == 1
    cleared = dict(conn.execute("SELECT sha256, quality IS NULL FROM file"))
    assert cleared["d" * 64] == 1  # .jpg, state 'read': this module can redo it
    assert cleared["e" * 64] == 0  # .svg: no decoder here, so not Phase 2b's error
    assert cleared["f" * 64] == 0  # still 'pending': its bytes have never been read


# --- restartability ----------------------------------------------------------


def test_the_run_is_idempotent_at_row_granularity(conn, config: Config, tmp_path: Path):
    sha = "1" * 64
    source = tmp_path / "obj.blob"
    source.write_bytes(jpeg(card(900, 600)))
    insert_file(conn, sha, ".jpg", source.stat().st_size, state="read", relpath="obj.blob")
    config = dataclasses.replace(config, mediavault_root=tmp_path)

    items = phase2b.worklist(conn, config)
    assert len(items) == 1
    sink = sink_for(conn, config)
    phase2b.run_images(items, sink, readers=1, decoders=1)

    assert phase2b.worklist(conn, config) == []  # a second run has nothing to do


# --- population 2: staging out of the photos root ----------------------------


def test_staging_is_content_addressed():
    path = phase2b.staging_path(Path(r"C:\v\.staging"), "ab" + "c" * 62)
    assert path == Path(r"C:\v\.staging\ab\cc") / ("ab" + "c" * 62 + ".blob")


def test_stage_copies_verifies_and_moves_the_row(conn, config: Config, tmp_path: Path):
    import hashlib

    config.photos_root.mkdir(parents=True)
    payload = jpeg(card(900, 600))
    sha = hashlib.sha256(payload).hexdigest()
    origin = config.photos_root / "holiday.jpg"
    origin.write_bytes(payload)
    insert_file(conn, sha, ".jpg", len(payload), state="pending", relpath=None)

    result = phase2b.stage_gap(conn, config, [(sha, str(origin), len(payload))], readers=1)

    assert result["staged"] == 1 and result["mismatched"] == [] and result["failed"] == []
    staged = phase2b.staging_path(config.staging_root, sha)
    assert staged.read_bytes() == payload
    assert origin.read_bytes() == payload  # the photos root is never written
    state, relpath = conn.execute(
        "SELECT state, vault_relpath FROM file WHERE sha256 = ?", (sha,)
    ).fetchone()
    assert state == "staged"
    assert relpath == str(staged.relative_to(config.vault_root))
    # And it now decodes from the staged copy, not from the photos root.
    assert phase2b.worklist(conn, config)[0].source == str(staged)


def test_a_staged_copy_that_does_not_verify_is_refused(conn, config: Config):
    config.photos_root.mkdir(parents=True)
    origin = config.photos_root / "changed.jpg"
    origin.write_bytes(b"these are not the bytes the catalog recorded")
    sha = "9" * 64
    insert_file(conn, sha, ".jpg", 43, state="pending", relpath=None)

    result = phase2b.stage_gap(conn, config, [(sha, str(origin), 43)], readers=1)

    assert len(result["mismatched"]) == 1 and result["staged"] == 0
    assert not phase2b.staging_path(config.staging_root, sha).exists()
    assert not list(config.staging_root.rglob("*.part"))
    assert conn.execute(
        "SELECT state, vault_relpath FROM file WHERE sha256 = ?", (sha,)
    ).fetchone() == ("pending", None)


def test_the_gap_worklist_is_what_triage_keeps(conn):
    """Population 2 is sized by the rule set, never by a fixed figure -- the
    8,052-file gap it was once sized by was a census artefact."""
    conn.executescript(
        "INSERT INTO triage_ext (id, ext) VALUES (1, '.jpg'), (2, '.tmp');"
        "INSERT INTO triage_root (id, root) VALUES (1, 'sd');"
        "INSERT INTO triage_dir (id, path, path_key) VALUES (1, 'G:\\p', 'g:\\p');"
    )
    for index, (sha, ext_id, state) in enumerate(
        [("a" * 64, 1, "pending"), ("b" * 64, 2, "pending"), ("c" * 64, 1, "read")], start=1
    ):
        insert_file(conn, sha, ".jpg", 10, state=state, relpath="x" if state == "read" else None)
        conn.execute(
            "INSERT INTO triage_bucket (id, dir_id, root_id, ext_id, camera, paths, bytes)"
            " VALUES (?,1,1,?,0,1,10)", (index, ext_id)
        )
        conn.execute("INSERT INTO origin (id, path, root, ext, size, sha256, seen_at)"
                     " VALUES (?,?, 'sd', '.jpg', 10, ?, 'now')", (index, f"G:\\p\\{index}", sha))
        conn.execute("INSERT INTO triage_path VALUES (?,?)", (index, index))

    rules = [triage.Rule(0, triage.predicate("ext", "=", ".tmp"), "exclude")]
    kept = phase2b.gap_worklist(conn, rules)

    # `.tmp` is excluded by the rule; the `read` file already has its bytes.
    assert [row[0] for row in kept] == ["a" * 64]


def test_an_override_beats_the_rules_in_the_gap_worklist(conn):
    conn.executescript(
        "INSERT INTO triage_ext (id, ext) VALUES (1, '.jpg');"
        "INSERT INTO triage_root (id, root) VALUES (1, 'sd');"
        "INSERT INTO triage_dir (id, path, path_key) VALUES (1, 'G:\\p', 'g:\\p');"
        "INSERT INTO triage_bucket (id, dir_id, root_id, ext_id, camera, paths, bytes)"
        " VALUES (1,1,1,1,0,1,10);"
        "INSERT INTO origin (id, path, root, ext, size, sha256, seen_at)"
        " VALUES (1, 'G:\\p\\1', 'sd', '.jpg', 10, '" + "a" * 64 + "', 'now');"
        "INSERT INTO triage_path VALUES (1,1);"
        "INSERT INTO state.triage_override VALUES ('" + "a" * 64 + "', 'include', 'now');"
    )
    insert_file(conn, "a" * 64, ".jpg", 10, state="pending", relpath=None)

    rules = [triage.Rule(0, triage.predicate("ext", "=", ".jpg"), "exclude")]
    assert [row[0] for row in phase2b.gap_worklist(conn, rules)] == ["a" * 64]


# --- bookkeeping -------------------------------------------------------------


def test_the_substrate_token_names_the_decode_path():
    local = phase2b.Item("a" * 64, ".dng", "x", staged=False)
    assert phase2b.substrate_token(local, "raw-halfdemosaic") == "deriv1536:raw-halfdemosaic"
    staged = phase2b.Item("a" * 64, ".jpg", "x", staged=True)
    assert phase2b.substrate_token(staged, "decode") == "deriv1536:decode:staged"


def test_feature_ver_merges_rather_than_replaces():
    merged = json.loads(phase2b._feature_ver(json.dumps({"meta": "adopted-v1"}), "deriv1536:decode"))
    assert merged["meta"] == "adopted-v1"
    assert merged["phash"].endswith("/deriv1536:decode")


def test_residue_says_which_formats_have_a_decoder(conn):
    insert_file(conn, "a" * 64, ".mp4", 1, state="read", relpath="x")
    insert_file(conn, "b" * 64, ".svg", 1, state="read", relpath="y")
    assert dict((ext, decodable) for ext, _n, decodable in phase2b.residue(conn)) == {
        ".mp4": True, ".svg": False
    }


def test_the_worklist_ignores_formats_with_no_decoder(conn, config: Config):
    insert_file(conn, "a" * 64, ".svg", 1, state="read", relpath="x")
    insert_file(conn, "b" * 64, ".jpg", 1, state="pending", relpath=None)
    assert phase2b.worklist(conn, config) == []


@needs_exiftool
def test_exiftool_reads_through_one_stay_open_process(tmp_path: Path):
    """One process for the whole run, and it survives more than one file."""
    exif = Image.Exif()
    exif[0x0131] = "Adobe Photoshop 25.0"
    first = tmp_path / "a.jpg"
    first.write_bytes(jpeg(card(900, 600), exif=exif))
    second = tmp_path / "b.jpg"
    second.write_bytes(jpeg(card(200, 100)))

    with phase2b.ExifTool(EXIFTOOL) as tool:
        pid = tool.proc.pid
        long_edge, software, history = phase2b._metadata_from_exif(tool.read(str(first)))
        assert (long_edge, software, history) == (900, "Adobe Photoshop 25.0", False)
        assert phase2b._metadata_from_exif(tool.read(str(second)))[0] == 200
        assert tool.proc.pid == pid  # the same process, not a second spawn


@needs_exiftool
def test_exiftool_gives_up_rather_than_hanging(tmp_path: Path):
    missing = tmp_path / "nothing-here.jpg"
    with phase2b.ExifTool(EXIFTOOL, timeout_s=5.0) as tool:
        assert phase2b._metadata_from_exif(tool.read(str(missing))) == (None, None, False)
